attention_head_size: 1
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels:
  event_name:
    Happy Hour: 1
    Lunch Hour Promo: 2
    Weekend Special: 3
    local_fair: 4
    music_fest: 5
    nan: 0
    promo_day: 6
  promotion_type:
    bogo: 1
    combo: 2
    discount: 3
    nan: 0
embedding_paddings:
- promotion_type
- event_name
embedding_sizes:
  event_name: !!python/tuple
  - 7
  - 5
  promotion_type: !!python/tuple
  - 4
  - 3
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: 10
log_val_interval: 1
lstm_layers: 1
max_encoder_length: 24
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
  add_nan: false
  classes_:
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - i8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      EAAAAAAAAAA=
    : 0
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      EQAAAAAAAAA=
    : 1
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      EwAAAAAAAAA=
    : 2
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      FAAAAAAAAAA=
    : 3
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      FQAAAAAAAAA=
    : 4
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      FgAAAAAAAAA=
    : 5
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      FwAAAAAAAAA=
    : 6
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      GAAAAAAAAAA=
    : 7
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      GQAAAAAAAAA=
    : 8
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      GgAAAAAAAAA=
    : 9
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      GwAAAAAAAAA=
    : 10
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      HAAAAAAAAAA=
    : 11
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      HQAAAAAAAAA=
    : 12
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      HgAAAAAAAAA=
    : 13
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      HwAAAAAAAAA=
    : 14
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      IAAAAAAAAAA=
    : 15
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      IQAAAAAAAAA=
    : 16
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      IgAAAAAAAAA=
    : 17
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      IwAAAAAAAAA=
    : 18
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      JAAAAAAAAAA=
    : 19
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      JQAAAAAAAAA=
    : 20
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      JgAAAAAAAAA=
    : 21
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      JwAAAAAAAAA=
    : 22
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      KAAAAAAAAAA=
    : 23
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      KQAAAAAAAAA=
    : 24
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      KgAAAAAAAAA=
    : 25
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      KwAAAAAAAAA=
    : 26
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      LAAAAAAAAAA=
    : 27
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      LQAAAAAAAAA=
    : 28
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      LgAAAAAAAAA=
    : 29
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      LwAAAAAAAAA=
    : 30
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      MAAAAAAAAAA=
    : 31
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      MQAAAAAAAAA=
    : 32
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      MgAAAAAAAAA=
    : 33
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      MwAAAAAAAAA=
    : 34
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      NAAAAAAAAAA=
    : 35
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      NQAAAAAAAAA=
    : 36
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      NgAAAAAAAAA=
    : 37
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      NwAAAAAAAAA=
    : 38
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      OAAAAAAAAAA=
    : 39
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      OQAAAAAAAAA=
    : 40
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      OgAAAAAAAAA=
    : 41
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      OwAAAAAAAAA=
    : 42
    ? !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      PAAAAAAAAAA=
    : 43
  classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 44
    - *id001
    - false
    - !!binary |
      EAAAAAAAAAARAAAAAAAAABMAAAAAAAAAFAAAAAAAAAAVAAAAAAAAABYAAAAAAAAAFwAAAAAAAAAY
      AAAAAAAAABkAAAAAAAAAGgAAAAAAAAAbAAAAAAAAABwAAAAAAAAAHQAAAAAAAAAeAAAAAAAAAB8A
      AAAAAAAAIAAAAAAAAAAhAAAAAAAAACIAAAAAAAAAIwAAAAAAAAAkAAAAAAAAACUAAAAAAAAAJgAA
      AAAAAAAnAAAAAAAAACgAAAAAAAAAKQAAAAAAAAAqAAAAAAAAACsAAAAAAAAALAAAAAAAAAAtAAAA
      AAAAAC4AAAAAAAAALwAAAAAAAAAwAAAAAAAAADEAAAAAAAAAMgAAAAAAAAAzAAAAAAAAADQAAAAA
      AAAANQAAAAAAAAA2AAAAAAAAADcAAAAAAAAAOAAAAAAAAAA5AAAAAAAAADoAAAAAAAAAOwAAAAAA
      AAA8AAAAAAAAAA==
  warn: true
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- encoder_length
time_varying_categoricals_decoder:
- promotion_type
- event_name
time_varying_categoricals_encoder:
- promotion_type
- event_name
time_varying_reals_decoder:
- time_idx
- hour
- day_of_week
- is_weekend
- staff_count
- promotion_flag
- event_flag
- inventory_alert
- relative_time_idx
time_varying_reals_encoder:
- time_idx
- hour
- day_of_week
- is_weekend
- staff_count
- promotion_flag
- event_flag
- inventory_alert
- relative_time_idx
- transactions
weight_decay: 0.0
x_categoricals:
- promotion_type
- event_name
x_reals:
- encoder_length
- time_idx
- hour
- day_of_week
- is_weekend
- staff_count
- promotion_flag
- event_flag
- inventory_alert
- relative_time_idx
- transactions
