embeddings {
  tensor_name: "promotion_type:01220"
  metadata_path: "01220/promotion_type\\metadata.tsv"
  tensor_path: "01220/promotion_type\\tensors.tsv"
}
embeddings {
  tensor_name: "event_name:01220"
  metadata_path: "01220/event_name\\metadata.tsv"
  tensor_path: "01220/event_name\\tensors.tsv"
}
